#!/bin/bash

# 🔐 CORREÇÃO ESPECÍFICA - redirect_uri_mismatch
echo "🔐 CORREÇÃO - redirect_uri_mismatch"
echo "=================================="
echo ""

echo "✅ PROGRESSO: O backend está funcionando!"
echo "❌ PROBLEMA: URL de callback não confere no Google Console"
echo ""

echo "🔍 DIAGNÓSTICO DO ERRO:"
echo "---------------------"
echo "Erro 400: redirect_uri_mismatch significa que:"
echo "1. Seu backend está enviando uma URL de callback"
echo "2. Mas essa URL NÃO está configurada no Google Cloud Console"
echo ""

echo "🎯 URLS DE CALLBACK POSSÍVEIS:"
echo "-----------------------------"
echo "Seu backend pode estar usando uma destas URLs:"
echo ""
echo "1. https://bindertcg-backend.onrender.com/auth/google/callback"
echo "2. https://sua-app-customizada.onrender.com/auth/google/callback"
echo "3. http://localhost:5000/auth/google/callback (se BACKEND_URL não estiver configurado)"
echo ""

echo "🔧 CORREÇÃO NO GOOGLE CLOUD CONSOLE:"
echo "====================================="
echo ""
echo "1. Acesse: https://console.cloud.google.com"
echo "2. Vá em: APIs & Services → Credentials"
echo "3. Clique no seu OAuth 2.0 Client ID"
echo "4. Em 'Authorized redirect URIs', ADICIONE TODAS estas URLs:"
echo ""
echo "   https://bindertcg-backend.onrender.com/auth/google/callback"
echo "   http://localhost:5000/auth/google/callback"
echo ""
echo "5. Clique 'SAVE'"
echo "6. Aguarde 5-10 minutos para propagação"
echo ""

echo "⚠️  IMPORTANTE:"
echo "Substitua 'bindertcg-backend' pela URL real do seu app no Render!"
echo ""

echo "🔍 DESCOBRIR A URL EXATA:"
echo "Se não souber a URL exata, execute:"
echo ""
echo "1. No painel do Render:"
echo "   - Clique no seu app"
echo "   - Copie a URL que aparece no topo"
echo ""
echo "2. Ou teste estas URLs no navegador:"
echo "   - https://bindertcg-backend.onrender.com/"
echo "   - https://seu-app.onrender.com/"
echo ""

echo "🧪 TESTE RÁPIDO:"
echo "==============="
echo "Execute este comando para ver qual URL seu backend usa:"
echo ""
echo "# Verificar se o backend responde:"
echo "curl -s https://bindertcg-backend.onrender.com/health"
echo ""
echo "# Se não funcionar, tente descobrir a URL correta:"
echo "curl -s https://seu-app-real.onrender.com/health"
echo ""

echo "📝 CONFIGURAÇÃO COMPLETA DO GOOGLE CONSOLE:"
echo "==========================================="
echo ""
echo "Authorized JavaScript origins:"
echo "  https://sua-app.vercel.app"
echo "  http://localhost:3000"
echo "  http://localhost:3001"
echo ""
echo "Authorized redirect URIs:"
echo "  https://bindertcg-backend.onrender.com/auth/google/callback"
echo "  http://localhost:5000/auth/google/callback"
echo ""

echo "✅ APÓS CONFIGURAR:"
echo "==================="
echo "1. Aguarde 5-10 minutos"
echo "2. Limpe cache do navegador"
echo "3. Teste o login novamente"
echo "4. Execute: ./test-auth.sh para verificar"
echo ""

echo "🆘 SE AINDA NÃO FUNCIONAR:"
echo "=========================="
echo "1. Confirme a URL exata do seu backend"
echo "2. Verifique se adicionou no Google Console"
echo "3. Aguarde mais tempo para propagação"
echo "4. Tente em janela anônima do navegador"
