#!/bin/bash

echo "🚀 BinderTCG - Setup Completo do Sistema OAuth + Backend"
echo "=========================================================="
echo ""

echo "✅ IMPLEMENTAÇÃO CONCLUÍDA:"
echo "- Google OAuth 2.0 Authentication"
echo "- Backend Node.js + Express + MongoDB"
echo "- Frontend React integrado"
echo "- Sistema de gerenciamento de decks na nuvem"
echo "- Sincronização automática de dados"
echo ""

echo "📋 PRÓXIMOS PASSOS PARA USAR O SISTEMA:"
echo ""

echo "1. 🔧 CONFIGURAR GOOGLE OAUTH:"
echo "   - Acesse: https://console.cloud.google.com/"
echo "   - Crie um projeto ou selecione existente"
echo "   - Habilite a 'Google+ API'"
echo "   - Vá em Credenciais → Criar credenciais → OAuth 2.0"
echo "   - URLs de origem autorizadas:"
echo "     * http://localhost:3000"
echo "     * http://localhost:5000"
echo "   - URLs de redirecionamento autorizadas:"
echo "     * http://localhost:5000/auth/google/callback"
echo "   - Copie CLIENT_ID e CLIENT_SECRET"
echo ""

echo "2. 📝 CONFIGURAR VARIÁVEIS DE AMBIENTE:"
echo "   Edite o arquivo: backend/.env"
echo "   - Substitua 'your_google_client_id_here' pelo seu CLIENT_ID"
echo "   - Substitua 'your_google_client_secret_here' pelo seu CLIENT_SECRET"
echo "   - Gere strings aleatórias para JWT_SECRET e SESSION_SECRET"
echo ""

echo "3. 🗄️ CONFIGURAR MONGODB:"
echo "   Opção A - Local:"
echo "   sudo apt install mongodb"
echo "   sudo systemctl start mongodb"
echo ""
echo "   Opção B - Atlas (nuvem):"
echo "   - Acesse: https://www.mongodb.com/atlas"
echo "   - Crie conta gratuita"
echo "   - Crie cluster"
echo "   - Configure usuário e obtenha string de conexão"
echo "   - Atualize MONGODB_URI no arquivo backend/.env"
echo ""

echo "4. 🚀 EXECUTAR O SISTEMA:"
echo "   Terminal 1 (Backend):"
echo "   cd backend && npm run dev"
echo ""
echo "   Terminal 2 (Frontend):"
echo "   npm start"
echo ""

echo "5. 🌐 ACESSAR APLICAÇÃO:"
echo "   - Frontend: http://localhost:3000"
echo "   - Backend: http://localhost:5000"
echo "   - Health Check: http://localhost:5000/health"
echo ""

echo "🎯 FUNCIONALIDADES IMPLEMENTADAS:"
echo "- ✅ Login seguro com Google"
echo "- ✅ Criação e gerenciamento de decks"
echo "- ✅ Adição/remoção de cartas dos decks"
echo "- ✅ Sincronização automática na nuvem"
echo "- ✅ Fallback para localStorage (offline)"
echo "- ✅ Interface responsiva"
echo "- ✅ Sistema de autenticação JWT"
echo "- ✅ Rate limiting e segurança"
echo ""

echo "📚 DOCUMENTAÇÃO COMPLETA:"
echo "Veja o arquivo SETUP_OAUTH.md para instruções detalhadas"
echo ""

echo "🐛 RESOLUÇÃO DE PROBLEMAS:"
echo "- Erro OAuth: Verifique credenciais no Google Cloud Console"
echo "- Erro MongoDB: Certifique-se que o MongoDB está rodando"
echo "- Erro CORS: Verifique se backend e frontend estão nas portas corretas"
echo ""

echo "✨ Pronto! Seu sistema BinderTCG com OAuth está configurado!"
